export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_REQUEST_SUCCESS = 'ADD_TODO_REQUEST_SUCCESS';
export const ADD_TODO_REQUEST_FAILED = 'ADD_TODO_REQUEST_FAILED';

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_REQUEST_SUCCESS = 'GET_TODOS_REQUEST_SUCCESS';
export const GET_TODOS_REQUEST_FAILED = 'GET_TODOS_REQUEST_FAILED';

